defaults:
  - robot: g1
  - controller: rl_policy
  - input: bvh
  - _self_

policy_hz: 50.0
pd_hz: 200.0
transition_duration: 2.0  # seconds to interpolate from default pose to motion command (0.0 to disable)
viewers: "sim2sim"
realtime: false
debug_trace_path: null
playback:
  pause_on_end: false
  keyboard:
    enabled: false

hydra:
  run:
    dir: .
